(source setenv;\
./misc/random_data.py |python ./run_stdin.py)
owned_dict 0 0 0 52061046 {0: {1: 4540448, 2: 815516472, 3: 325002959, 4: 445105719, 5: 674778245, 6: 896556445, 7: 945728947, 8: 629297159, 9: 895019542}, 1: {0: 854937460, 1: 225594218, 2: 934974401, 3: 326830667, 4: 264206409, 5: 527493350, 6: 389652636, 7: 650766045, 8: 599925716, 9: 19017694}, 2: {0: 579270954, 1: 846306395, 2: 794362277, 3: 681868715, 4: 721325570, 5: 773257507, 6: 780821503, 7: 985425449, 8: 251048808, 9: 30502400}, 3: {0: 517795701, 1: 424346796, 2: 878857965, 3: 361291381, 4: 388901484, 5: 510496154, 6: 273458263, 7: 968035940, 8: 735713480, 9: 195318620}, 4: {0: 541887096, 1: 17735551, 2: 87202526, 3: 390072287, 4: 289949879, 5: 296282982, 6: 426201282, 7: 498877435, 8: 825674694, 9: 980653482}, 5: {0: 977885854, 1: 979492066, 2: 441836917, 3: 162942412, 4: 815278083, 5: 168278365, 6: 957660671, 7: 262564661, 8: 420867031, 9: 328543183}, 6: {0: 54484612, 1: 120337870, 2: 326262423, 3: 250494724, 4: 160866667, 5: 283296892, 6: 860838169, 7: 935228331, 8: 614136132, 9: 714441806}, 7: {0: 722119971, 1: 474583542, 2: 15290645, 3: 10991520, 4: 779024516, 5: 475256451, 6: 231774272, 7: 28849481, 8: 83973899, 9: 521038836}, 8: {0: 395625679, 1: 638479061, 2: 842688502, 3: 236087287, 4: 971307883, 5: 8515950, 6: 107734074, 7: 187242171, 8: 50898009, 9: 263796047}, 9: {0: 400604250, 1: 408859956, 2: 239472963, 3: 313764690, 4: 749798580, 5: 285363277, 6: 150535498, 7: 94989279, 8: 443543911, 9: 999631510}}
makefile:20: recipe for target 'run_large' failed
